spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 3DX4N7v8Mkgpzox1N5VTQICU5oIvCFvH
            client-secret: YOUR_CLIENT_SECRET
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://robertify.us.auth0.com/